Clear lastCommits after fixTxOffset
On gitter, a user reported

```
Failed to correct transactional offset(s)
java.lang.IllegalStateException: You can only check the position for partitions assigned to this consumer.
```

It is not clear how this happened since we remove revoked partitions from `lastCommits`.

However, `lastCommits` should be cleared, even if successful, to avoid unnecessary
processing if no records are received by the next poll.

- add the `lastCommits` to the error log
- clear `lastCommits` in a finally block

**cherry-pick to 2.5.x**