Bump to the latest BUILD-SNAPSHOTs
After introducing a `BeanDefinition.getResolvableType()` we have
several failed builds because of `NoSuchMethodError`.
Looks like interface and its implementation classes are loaded from
different versions.

* Exclude `org.springframework` from `spring-data-commons` to avoid
CLASSPATH conflicts

Related to
https://build.spring.io/browse/SK-SON-1242/
https://github.com/spring-projects/spring-framework/issues/23178